name: Test V1

on:
  push:
    branches:
      - v1
  schedule:
    - cron: '*/15 * * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php_version: [ 7.4, 8.0, 8.1 ]

    steps:
      - uses: actions/checkout@v2
        with:
          ref: v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_version }}
          #extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, redis
          tools: composer:v2
          coverage: none

      - name: Run composer install
        run: composer install -n --prefer-dist

      - name: Run unit and functional tests
        run: |
          php vendor/bin/phpunit --stop-on-failure
        env:
          STORAGENAME: ${{ secrets.STORAGENAME }}
          APIKEY: ${{ secrets.APIKEY }}
